### ISSUE TITLE
Shared files are not synced correctly on host and guest

### ISSUE THREAD

**Issue by ianbytchek** [Parallels/docker-machine-parallels#12] opened 2015-11-10 09:18 UTC
I was having a nasty [issue](https://github.com/kitematic/kitematic/issues/605) with VirtualBox / Kitematic awhile ago, which resulted in files stopping syncing across host and vm. I've seen a few related issues in the past, but never found this exact one. On the left is the file I've just updated on host, on the right is the same file but inside boot2docker vm running on parallels driver.

![image](https://cloud.githubusercontent.com/assets/1086845/11058494/54c7259c-87a4-11e5-86bb-f458a71f6ab2.png)

As I was typing, the file got synced with the host about 20 min later after I changed it. This is better than VirtualBox, as it never happened in there. I had to reboot the host os to see the effects or use some hacks like move the file from within the guest (see the aforementioned issue). The biggest problem with this is that it's completely inconsistent. It might be happening after vm wasn't touched for awhile, probably after going to sleep a few times and not updating the given file. I never was able to reproduce this 100% to provide clear steps.

Because of this I cannot use shared volumes to full capacity. That's already a huge problem with a single configuration file, scared to think what might go wrong when I save an entire database on a mounted volume. Is there any theoretical reason why this might be happening and how to trace this down? May this be a problem with boot2docker itself?

**Comment by krasilich** [comment] 2015-11-10 10:46
Hi Ian,
personally I switched from native shared folder implementation of Parallels/VirtualBox to nfs.
As for me nfs is little bit faster and reliable.
Just try this script https://github.com/adlogix/docker-machine-nfs it works with VirtualBox and Parallels

Further reading https://github.com/boot2docker/boot2docker/issues/581 you might find another approaches there

**Comment by romankulikov** [comment] 2015-11-10 11:14
Ian, do I understand correctly that "typical" situation is something like this:
0. `host $ sed 's/foo/bar/' file`
1. `vm $ grep bar file # not found`
Waiting 20 minutes...
2. `vm $ grep bar file # found`
?

**Comment by ianbytchek** [comment] 2015-11-10 12:21
@krasilich I've heard about it briefly before. Will give it a try, thanks!

**Comment by ianbytchek** [comment] 2015-11-10 12:31
@romankulikov no, in those cases everything normally works. I've only observed this with existing files. A typical scenario.

0. Create config, launch a container with that config mounted as a volume `/foo/bar.json:/foo/bar.json`.
0. Don't touch it for awhile, sometimes a few minutes, sometimes a few days.
0. Change the file, check it on guest – there it would normally appear unchanged.

Some interesting [observations](https://github.com/kitematic/kitematic/issues/605#issuecomment-111401366) were done on VirtualBox, like `cat` would returned old file, but `vi` would show updated file. Often updated file inside vm would appear outdated inside a container. I didn't play much with this on parallels, but the issues is definitely there.

**Comment by romankulikov** [comment] 2015-11-10 12:53
@ianbytchek grasped. Thanks! Will try to reproduce.

**Comment by ianbytchek** [comment] 2015-11-10 12:56
@romankulikov let me know if I can be of help.

**Comment by romankulikov** [comment] 2015-11-17 13:31
@ianbytchek I'm still trying to reproduce the issue but no luck, everything works for now.  I have a couple of questions:
0. what versions of products do you using (I mean Parallels Desktop, boot2docker, docker-machine)?
1. how do you edit file on the host side?

**Comment by ianbytchek** [comment] 2015-11-17 13:49
All the latest as of now, pretty much always the latest. Just open up the file with sublime, occasionally with atom, edit and save. Noting unusual. 

Apparently one thing that I was doing wrong all that time was starting the vm directly through Parallels / VirtualBox, oppose to starting it with docker machine command. @legal90 pointed out recently that there are extra steps, which I guess might have an effect, so I'm keeping an eye on that. I do find it very strange that I seem to be the only one affected by that, so it's likely to be my fault. Feel free to close this, if I stumble upon this again with vm started through docker-machine, I'll report.

**Comment by romankulikov** [comment] 2015-11-17 14:09
Frankly speaking I don't think issue is caused by VM startup way. My current hypothesis is that text editor changes inode of file being edited. That's why you don't get recent update of file's contents in container. I've tried both Sublime and Atom: they seem not relinking edited file. But this may not be true for some cases I'm not aware of.

It would be great you trace file inode number before and after issue reproduction.

**Comment by romankulikov** [comment] 2015-11-26 10:32
@ianbytchek any news on the issue?

**Comment by ianbytchek** [comment] 2015-11-26 10:48
Apologies, v. busy with something else. I come across the issue every once in a while, waiting for that to happen and definitely not forgetting about reporting it :grimacing:

**Comment by legal90** [comment] 2015-12-28 17:22
> Feel free to close this, if I stumble upon this again with vm started through docker-machine, I'll report.

OK, I close it. Please, let us know if you will run into this issue again.

**Closed by legal90** 2015-12-28 17:22 UTC

**Comment by ianbytchek** [comment] 2015-12-30 18:21
Didn't have a chance to work closely on this in the past month, will come back with details when see this again. I see there's a bunch of issues that sound pretty similar.
