### ISSUE TITLE
Error creating Docker machine

### ISSUE THREAD

**Issue by d8vjork** [Parallels/docker-machine-parallels#85] opened 2020-03-03 20:05 UTC
![image](https://user-images.githubusercontent.com/2331052/75814804-4acc6280-5d8a-11ea-8661-733d76fa2a7d.png)

Checked Parallels and the machine is there, try as well removing and recreating, restarting and nothing yet.

Apparently always fails when it try to check if the machine is running and which version of Docker is it.

Parallels version: 15.1.2
Docker version: 19.03.5

**Comment by legal90** [comment] 2020-04-26 18:08
@d8vjork Does the directory `/Library/Preferences/Parallels` exist and not empty?

**Comment by d8vjork** [comment] 2020-04-26 20:41
@legal90 Yeah, it does exists and with some files inside

**Comment by legal90** [comment] 2020-04-27 05:59
I tried to reproduce this issue by deleting `/Library/Preferences/Parallels/parallels_dhcp_leases` and creating a new docker-machine VM:
```
docker-machine --debug create -d parallels test-vm
```
I see the same output as you, but then after 8th attempt this file is found and docker-machine proceeds. That's normal, because `parallels_dhcp_leases` is created automatically when the first VM starts up and requests its IP address by DHCP.

@d8vjork What do you see in your case further? Does it reach 60th attempt and fails with timeout? What do you in the VM GUI window then?

**Comment by legal90** [comment] 2020-10-14 06:37
Hi @d8vjork, Do you still have this issue, or we can close it?

**Comment by legal90** [comment] 2020-12-10 13:25
I'm closing this issue due to inactivity. Feel free to create a new issue if it's still actual

**Closed** 2020-12-10 13:24 UTC
